// Dummy product data
export const DUMMY_PRODUCTS = [
  {
    id: 1,
    name: "Premium Denim Jeans",
    price: 2499,
    sale_price: 1999,
    image: "/products/jeans.jpg",
    category: "Jeans",
    description: "Classic blue denim jeans with comfortable fit and durability",
    stock_status: "instock",
    images: [{ src: "/products/jeans.jpg" }],
  },
  {
    id: 2,
    name: "Casual Cotton Shirt",
    price: 1299,
    sale_price: null,
    image: "/products/shirt.jpg",
    category: "Shirt",
    description: "Breathable cotton shirt perfect for any occasion",
    stock_status: "instock",
    images: [{ src: "/products/shirt.jpg" }],
  },
  {
    id: 3,
    name: "Formal Business Suit",
    price: 5999,
    sale_price: 4999,
    image: "/products/suit.jpg",
    category: "Suit",
    description: "Professional business suit made from premium fabric",
    stock_status: "instock",
    images: [{ src: "/products/suit.jpg" }],
  },
  {
    id: 4,
    name: "Graphic T-Shirt",
    price: 599,
    sale_price: 399,
    image: "/products/tshirt.jpg",
    category: "T Shirt",
    description: "Comfortable graphic printed t-shirt",
    stock_status: "instock",
    images: [{ src: "/products/tshirt.jpg" }],
  },
  {
    id: 5,
    name: "Traditional Kamiz Shalwar",
    price: 2999,
    sale_price: 2499,
    image: "/products/kamiz.jpg",
    category: "Kamiz Shalwar",
    description: "Elegant traditional kamiz shalwar set",
    stock_status: "instock",
    images: [{ src: "/products/kamiz.jpg" }],
  },
  {
    id: 6,
    name: "Winter Jacket",
    price: 3999,
    sale_price: null,
    image: "/products/jacket.jpg",
    category: "Jacket",
    description: "Warm and stylish winter jacket",
    stock_status: "instock",
    images: [{ src: "/products/jacket.jpg" }],
  },
  {
    id: 7,
    name: "Chino Pants",
    price: 1699,
    sale_price: 1299,
    image: "/products/pant.jpg",
    category: "Pant",
    description: "Comfortable chino pants for casual wear",
    stock_status: "instock",
    images: [{ src: "/products/pant.jpg" }],
  },
  {
    id: 8,
    name: "Sport Shoes",
    price: 2999,
    sale_price: 2299,
    image: "/products/shoes.jpg",
    category: "Shoes",
    description: "Comfortable sport shoes for everyday use",
    stock_status: "instock",
    images: [{ src: "/products/shoes.jpg" }],
  },
  {
    id: 9,
    name: "Classic Blue Jeans",
    price: 2299,
    sale_price: 1699,
    image: "/products/jeans.jpg",
    category: "Jeans",
    description: "Timeless blue jeans with perfect fit",
    stock_status: "instock",
    images: [{ src: "/products/jeans.jpg" }],
  },
  {
    id: 10,
    name: "Summer T-Shirt",
    price: 699,
    sale_price: null,
    image: "/products/tshirt.jpg",
    category: "T Shirt",
    description: "Light and breathable summer t-shirt",
    stock_status: "instock",
    images: [{ src: "/products/tshirt.jpg" }],
  },
  {
    id: 11,
    name: "Casual Shirt",
    price: 1499,
    sale_price: 999,
    image: "/products/shirt.jpg",
    category: "Shirt",
    description: "Casual shirt for everyday wear",
    stock_status: "instock",
    images: [{ src: "/products/shirt.jpg" }],
  },
  {
    id: 12,
    name: "Leather Jacket",
    price: 4999,
    sale_price: 3999,
    image: "/products/jacket.jpg",
    category: "Jacket",
    description: "Premium leather jacket for style",
    stock_status: "instock",
    images: [{ src: "/products/jacket.jpg" }],
  },
];

export const CATEGORIES = [
  "All",
  "Jeans",
  "Shirt",
  "Suit",
  "T Shirt",
  "Kamiz Shalwar",
  "Jacket",
  "Pant",
  "Shoes",
];

export const FEATURED_CATEGORIES = [
  { name: "Jeans", image: "/products/jeans.jpg" },
  { name: "Shirt", image: "/products/shirt.jpg" },
  { name: "Suit", image: "/products/suit.jpg" },
  { name: "T Shirt", image: "/products/tshirt.jpg" },
  { name: "Kamiz Shalwar", image: "/products/kamiz.jpg" },
  { name: "Jacket", image: "/products/jacket.jpg" },
  { name: "Pant", image: "/products/pant.jpg" },
  { name: "Shoes", image: "/products/shoes.jpg" },
];
